# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ae6f8f3ad4670ac67eca80300630225e6a72c3308d493bed5d49d0766f3da915f10c9c3f792f1393f4f4dfd3734a2a4a75a0957ae8fdf7f6b96cddb150748e

test:
  secret_key_base: 9ac62c94425003bc2da13dbaaa89fbceaa753698973f8d1765aaaf297274eccd076b5d6b5b9a548392fe1316b88e6ad8754613cb5bb67956046a0171bfa595a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
